version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:password@db:5432/gctl
      PGRST_DB_SCHEMAS: gctl
      PGRST_DB_ANON_ROLE: postgres
      #PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gctl
      POSTGRES_PASSWORD: password
    volumes:
      - "./database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql" # create database when postgres container starts
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080