version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    environment:
      - PGRST_DB_URI
      - PGRST_DB_SCHEMAS
      - PGRST_DB_ANON_ROLE
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - "./database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql" # create database when postgres container starts
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
  gctl-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mva-one/gctl-server
    restart: always
    ports:
      - "3001:3001"